name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test
    - name: pwd
      run: pwd
    - name: ls
      run: ls build/libs
    - name: mkdir
      run:  sudo mkdir /var/lib/docker/tmp/docker-builder456386987/
    - name: ls
      run: ls
    - name: docker images
      run: sudo docker images

 
    - uses: actions/checkout@master
    - name: pwd
      run: pwd
    - name: ls
      run: ls
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: shijupjohn/newdb1:v1
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
