name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test
    - name: Upload jar file
      uses: actions/upload-artifact@v1
      with:
        name: jarfile
        path: build/libs/
 
    - uses: actions/checkout@master
    - name: Download jar file
      uses: actions/download-artifact@v1
      with:
        name: jarfile
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: shijupjohn/newdb1:v1
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.EC2_HOST }}
       username: ${{ secrets.EC2_USERNAME }}
       key: ${{ secrets.EC2_KEY }}
       port: ${{ secrets.EC2_PORT }}
       script: |
        sudo docker stop newdbcontainer
        sudo docker pull shijupjohn/newdb1:v1
        sudo docker run -d -p 8080:8080 --network=host --name newdbcontainer shijupjohn/newdb1:v1
