name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test
    - name: pwd
      run: pwd
    - name: ls
      run: ls build/libs
    - name: ls
      run: ls
    - name: docker images
      run: sudo docker images

    - uses: mr-smithers-excellent/docker-build-push@v2
      with:
       image: shijupjohn/newdb1:v1
       tag: latest
       registry: registry-url.io
       dockerfile: Dockerfile
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
