name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.EC2_HOST }}
       username: ${{ secrets.EC2_USERNAME }}
       key: ${{ secrets.EC2_KEY }}
       port: ${{ secrets.EC2_PORT }}
       script: |
        sudo docker stop newdbcontainer
        sudo docker system prune -f
        sudo docker pull shijupjohn/newdb1:v1
        sudo docker run -d -p 8080:8080 --network=host --name newdbcontainer shijupjohn/newdb1:v1
